platform :android do
    desc 'Build the Android application.'
    lane :build do
      gradle(task: 'clean', project_dir: 'android/')
      gradle(task: 'assemble', build_type: 'debug', project_dir: 'android/')
    end


    desc 'Build and upload to App Center.'
    lane :beta do
    build
    appcenter_upload(
        api_token: "7f030f375b4f9efda218c60c9febf0e53260cb09",
        owner_name: "vishal.gogawale-expleogroup.com",
        app_name: "MyFirstApp",
        apk: "./android/app/build/outputs/apk/debug/app-debug.apk"
        )
    end
end

platform :ios do    
  desc 'Fetch certificates and provisioning profiles'
  lane :certificates do
    match(app_identifier: 'com.expleo.appmob')
  end
  desc 'Build IOS application'
  lane :build_stagging_ios do
    cocoapods(podfile: "./ios/Podfile")
    certificates
    gym(
      scheme: 'myfirstapp', 
      project: './ios/myfirstapp.xcodeproj',
      clean: true, 
      workspace: './ios/myfirstapp.xcworkspace', 
      export_method: 'development', 
      output_directory: './builds'
    
  )
  end
  desc 'Build IOS application and upload to appcenter'
  lane :ios_beta do
    build_stagging_ios
    appcenter_upload(
      api_token: "7f030f375b4f9efda218c60c9febf0e53260cb09",
          owner_name: "vishal.gogawale-expleogroup.com",
          app_name: "MyFirstApp_ios",
          ipa: "./builds"
    )
  end
end
